#!/bin/bash

hyprctl workspaces -j | jq -c --argjson active $(hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id') 'sort_by(.id) | map({id:.id,windows:.windows,active:($active == .id)})'

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}' | while read -r active; do
	hyprctl workspaces -j | jq -c --argjson active $active 'sort_by(.id) | map({id:.id,windows:.windows,active:($active == .id)})'
done
