[class]
image_default = [
	{ command = "qimgv", fork = true, silent = true },
	{ command = "krita", fork = true, silent = true },
]

[extension]
# inherit from image_default class
png.inherit = "image_default"

# inherit from image_default class
jpg.inherit = "image_default"
# in addition, also add gimp for .jpg files only
jpg.app_list = [{ command = "gimp", fork = true, silent = true }]

mkv.app_list = [
	{ command = "mpv", args = [
		"--",
	], fork = true, silent = true },
	{ command = "mediainfo", confirm_exit = true },
	{ command = "mpv", args = [
		"--mute",
		"on",
		"--",
	], fork = true, silent = true },
]
rs.app_list = [
	{ command = "micro" },
	{ command = "gedit", fork = true, silent = true },
	{ command = "bat", confirm_exit = true },
]

[mimetype]

# text/*
[mimetype.text]
inherit = "text_default"

# application/octet-stream
[mimetype.application.subtype.octet-stream]
inherit = "video_default"
